resources:
- name: jaipur
  type: git
  source:
    uri: https://github.com/belljustin/jaipur.git
    branch: master

jobs:
- name: build-jaipur-client
  public: true
  plan:
  - get: jaipur
    trigger: true
  - task: build-client
    file: jaipur/ci/build_client.yml

- name: build-jaipur-server
  public: true
  plan:
  - get: jaipur
    trigger: true
  - task: build-server
    file: jaipur/ci/build_server.yml
